output_folder: "../logs"
dataset:
  img_folder: "../data/VOCdevkit/VOC2007/JPEGImages"
  json_folder: "../data"

model:
  # backbone: resnet34
  # fpn_feats_dim: 128
  backbone: resnet152
  backbone_out_feats_dims: [512, 1024, 2048]
  fpn_feats_dim: 256
  backbone_freeze_bn: True

input:
  img_min_size: [800, 832, 864]
  img_max_size: 1280

loader:
  batch_size: 6
  num_workers: 8

opt:
  # 1x schedule: mAP@IoU=0.5 ~61%
  warmup_epochs: 5
  epochs: 100
  learning_rate: 0.0025

test_cfg:
  score_threshold: 0.08
  

# other parameters can be specified in this yaml file
# e.g. the following lines will reset the number of training epochs to 8
#opt:
#  epochs: 8

# see config.py for more details
